### ISSUE TITLE
CCU2

### ISSUE THREAD

**Issue by taucher4000** [hobbyquaker/ccu-addon-mosquitto#5]
Can you confirm that this addon is not running on CCU2? I've installed it but whenever I try to run the command, I get the  following message:

# /usr/local/bin/mosquitto
-sh: /usr/local/bin/mosquitto: not found

However, the binaries are there:
# ls -ls /usr/local/bin/
total 0
     0 lrwxrwxrwx    1 root     root            41 Sep 24 20:59 mosquitto -> /usr/local/addons/mosquitto/bin/mosquitto
     0 lrwxrwxrwx    1 root     root            48 Sep 24 20:59 mosquitto_passwd -> /usr/local/addons/mosquitto/bin/mosquitto_passwd
     0 lrwxrwxrwx    1 root     root            45 Sep 24 20:59 mosquitto_pub -> /usr/local/addons/mosquitto/bin/mosquitto_pub
     0 lrwxrwxrwx    1 root     root            45 Sep 24 20:59 mosquitto_sub -> /usr/local/addons/mosquitto/bin/mosquitto_sub

**Comment by hobbyquaker** [comment]
Yes, I can confirm that only works on a CCU3 or RaspberryMatic. The CCU2 CPU has no hardfloat unit and another arm instruction set.
