### ISSUE TITLE
Mosquitto von extern mit Daten versorgen

### ISSUE THREAD

**Issue by FordAndii** [hobbyquaker/ccu-addon-mosquitto#6]
Hallo, ich taste mich gerade erstmals an MQTT heran. Sorry für den Doppelpost, aber unter https://homematic-forum.de/forum/viewtopic.php?f=41&t=49638 habe ich bisher keine Antwort erhalten.

Ich möchte Owntracks zur Anwesenheitserkennung usw. einsetzen. Owntracks erfordert ja einen MQTT-Server, an den ich die Positionsdaten sende. Ist es praktikabel, hierfür Mosquitto als Addon auf der CCU3 einzusetzen? Gibt es eine sichere und einfache Variante, die Positionsdaten aus dem Internet an mein Mosquitto zu senden? Oder ist das der "falsche" Anwendungsfall und Mosquitto nur dazu gedacht, heimnetzintern die MQTT-Kommunikation abzuwickeln, sodass ich stattdessen einen externen MQTT-Server außerhalb meines Heimnetzwerks einsetzen muss?

**Comment by hobbyquaker** [comment]
Ich würde davon abraten den Mosquitto auf der CCU ins Internet zu stellen. Besser so vorgehen:
einen zweiten Broker auf einem gemieteten vServer oder ein kostenlosen Broker wie z.B. https://www.cloudmqtt.com nutzen und Owntracks dorthin publishen lassen. Dann in Node-RED die Topics von diesem Broker subscriben und auf Deinem lokalen Broker wieder publishen.

**Comment by FordAndii** [comment]
Danke für die schnelle Antwort! Eine Verständnisfrage noch: Wozu benötige ich bei der Lösung noch einen lokalen Broker? Kann ich nicht die Daten, die sich Node-RED vom Internet-Broker zieht, direkt in Node-RED verarbeiten?

**Comment by hobbyquaker** [comment]
Wenn Du außer Owntracks nichts mit MQTT machst kannst auf den lokalen Broker verzichten.

**Comment by FordAndii** [comment]
Perfekt, danke!
