### ISSUE TITLE
Moquitto Addon mit RaspberryMatic 3.45.5.20190330 

### ISSUE THREAD

**Issue by vore** [hobbyquaker/ccu-addon-mosquitto#7]
Hallo!
Nach dem Update auf RaspberryMatic 3.45.5.20190330 läuft das Mosquitto-Addon auf der CCU nicht mehr (keine Verbindung über MQTTfx möglich). 
Nach der Aussage von Jens Maus im Homematic Forum könnte es mit den neueren Buildroot zusammenhängen. Siehe auch diese Post von Jens: [](url)https://homematic-forum.de/forum/viewtopic.php?f=65&t=49960&start=70#p501086
Könntest Du das bitte prüfen?
Danke!
Vore

**Comment by dpunzeng** [comment]
Hallo, hatte gestern auch troubles mit RedMatic - uU selbe Ursache

**Comment by vore** [comment]
Hallo!
Hier geht es um das Moquitto Addon.. nicht Redmatic.. nur zur Sicherheit.

**Comment by hobbyquaker** [comment]
@vore Schau mal bitte ob das Problem mit 1.5.8+0 gelöst ist: https://github.com/hobbyquaker/ccu-addon-mosquitto/releases/tag/1.5.8%2B0

**Comment by vore** [comment]
@hobbyquaker: sieht gut aus! Verbindung wird aufgebaut. Die installierte Version in der CCU bleibt aber 1.4.15+15. Vermutlich ein Versionstag noch nicht angepasst?

**Comment by RonMeier** [comment]
kann ich bestätigen, es läuft wieder. Nach der Installation von Mosqitto ist es aber zwingend notwendig, dass der Raspi neu gestartet wird, damit der Mosquitto - Dienst läuft.
Vielen Dank für die schnelle Reaktion!
