### ISSUE TITLE
libraries in /usr/local/lib are breaking a lot of stuff

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/ccu-addon-mosquitto#8]

**Comment by hobbyquaker** [comment]
@Christoph22 Check mal bitte ob Version 1.5.8+2 das Problem behebt.

**Comment by Christoph22** [comment]
# npm install node-ical
Unhandled rejection Error: EROFS: read-only file system, mkdir '/root/.npm'2587c

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

**Comment by hobbyquaker** [comment]
Oh. Das ist nochmal ein anderes Problem jetzt :-)

Wie Du auf der Commandline npm nutzen kannst ist hier beschrieben: https://github.com/rdmtc/RedMatic/wiki/Node-Installation#Installation-via-npm-auf-der-Kommandozeile

**Comment by Christoph22** [comment]
Danke, funktioniert
